# Generated by Django 2.1.1 on 2019-05-07 11:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicleviolation',
            old_name='is_done',
            new_name='is_processed',
        ),
    ]
