# Generated by Django 2.1.1 on 2019-05-09 19:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicledetection',
            name='original_frame',
        ),
    ]
