# Generated by Django 2.0.6 on 2019-05-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numberplatedetection',
            name='number_plate',
        ),
        migrations.RemoveField(
            model_name='vehiclemonitor',
            name='is_done',
        ),
        migrations.AddField(
            model_name='vehicledetection',
            name='original_path',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
