# Generated by Django 2.1.1 on 2019-04-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='label_path',
            field=models.FileField(default=0, max_length=1000, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='violationmaster',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='violationmaster',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
