# Generated by Django 2.1.1 on 2019-05-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Dashboard', '0002_remove_vehicledetection_original_frame'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledetection',
            name='original_frame',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
