# Generated by Django 2.1.1 on 2019-05-07 12:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Dashboard', '0003_auto_20190507_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='input',
            old_name='location',
            new_name='camera',
        ),
    ]
