# Generated by Django 2.1.1 on 2019-05-01 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('Dashboard', '0004_auto_20190501_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=15, null=True)),
                ('mobile', models.PositiveIntegerField(default='8554951545')),
                ('address', models.CharField(default='test', max_length=250)),
                ('image', models.FileField(max_length=1000, upload_to='')),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleTypeMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vehicledetection',
            name='address',
        ),
        migrations.RemoveField(
            model_name='vehicledetection',
            name='is_done',
        ),
        migrations.RemoveField(
            model_name='vehicledetection',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='vehicledetection',
            name='number',
        ),
        migrations.RemoveField(
            model_name='vehicledetection',
            name='type',
        ),
        migrations.AddField(
            model_name='vehicledetection',
            name='location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.Camera'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicledetection',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='vehicleviolation',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.VehicleMonitor'),
        ),
        migrations.AddField(
            model_name='vehiclemonitor',
            name='vehicel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.VehicleTypeMaster'),
        ),
        migrations.AddField(
            model_name='vehicledetection',
            name='vehicle_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE,
                                    to='Dashboard.VehicleTypeMaster'),
            preserve_default=False,
        ),
    ]
