# Generated by Django 2.1.1 on 2019-05-07 12:25

import Dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Dashboard', '0004_auto_20190507_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberplatedetection',
            name='image',
            field=models.FileField(max_length=1000, upload_to=Dashboard.models.number_plate_directory),
        ),
    ]
