# Generated by Django 2.1.1 on 2019-05-07 12:29

import Dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Dashboard', '0005_auto_20190507_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledetection',
            name='image',
            field=models.FileField(max_length=1000, upload_to=Dashboard.models.vehicle_detection_directory),
        ),
    ]
