# Generated by Django 2.1.1 on 2019-05-01 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('Dashboard', '0005_auto_20190501_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.Camera'),
            preserve_default=False,
        ),
    ]
