# Generated by Django 2.1.1 on 2019-05-01 16:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Dashboard', '0006_input_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detection',
            old_name='label_path',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='detection',
            old_name='model_path',
            new_name='model',
        ),
    ]
