# Generated by Django 2.1.1 on 2019-05-07 12:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Dashboard', '0006_auto_20190507_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numberplatedetection',
            name='number_plate',
        ),
    ]
