# Generated by Django 2.1.1 on 2019-05-01 16:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Dashboard', '0007_auto_20190501_1620'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detection',
            new_name='Model',
        ),
    ]
