# Generated by Django 2.1.1 on 2019-05-01 17:41

import Dashboard.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('Dashboard', '0008_auto_20190501_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='label',
            field=models.FileField(max_length=1000, upload_to=Dashboard.models.label_directory),
        ),
        migrations.AlterField(
            model_name='model',
            name='model',
            field=models.FileField(max_length=1000, upload_to=Dashboard.models.model_directory),
        ),
        migrations.AlterField(
            model_name='vehicledetection',
            name='image',
            field=models.ImageField(upload_to=Dashboard.models.vehicle_detection_directory),
        ),
        migrations.AlterField(
            model_name='vehicledetection',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.Camera'),
        ),
        migrations.AlterField(
            model_name='vehiclemonitor',
            name='image',
            field=models.FileField(max_length=1000, upload_to=Dashboard.models.vehicle_monitor_directory),
        ),
    ]
