# Generated by Django 2.1.1 on 2019-05-01 18:18

import Dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Dashboard', '0009_auto_20190501_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledetection',
            name='image',
            field=models.FileField(upload_to=Dashboard.models.vehicle_detection_directory),
        ),
    ]
