# Generated by Django 2.1.1 on 2019-05-07 11:15

import Dashboard.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('Dashboard', '0011_auto_20190507_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberPlateDetection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=Dashboard.models.vehicle_detection_directory)),
                ('is_processed', models.BooleanField(default=False)),
                ('vehicle_detection',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.VehicleDetection')),
            ],
        ),
    ]
